-- MySQL Script generated by MySQL Workbench
-- Sun Sep 14 15:56:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `idAluno` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeAluno` VARCHAR(45) NOT NULL,
  `matriculaAluno` INT(11) NOT NULL,
  `turmaAluno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAluno`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`chamada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chamada` (
  `idChamada` INT(11) NOT NULL,
  `dataChamada` DATETIME NOT NULL,
  `provaSubstitutivasChamada` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idChamada`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `idProfessor` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeProfessor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfessor`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina` (
  `idDisciplina` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeDisciplina` VARCHAR(45) NOT NULL,
  `professor_idProfessor` INT(11) NOT NULL,
  PRIMARY KEY (`idDisciplina`),
  INDEX `fk_Disciplina_professores1_idx` (`professor_idProfessor` ASC),
  CONSTRAINT `fk_Disciplina_professores1`
    FOREIGN KEY (`professor_idProfessor`)
    REFERENCES `mydb`.`professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `idFuncionario` INT(11) NOT NULL AUTO_INCREMENT,
  `emailFuncionario` VARCHAR(45) NOT NULL,
  `senhaFuncionario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`provas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`provas` (
  `idProvas` INT(11) NOT NULL AUTO_INCREMENT,
  `Provascol` VARCHAR(45) NULL DEFAULT NULL,
  `professor_idProfessor` INT(11) NOT NULL,
  `dataProva` DATETIME NOT NULL,
  PRIMARY KEY (`idProvas`),
  INDEX `fk_Provas_professor1_idx` (`professor_idProfessor` ASC),
  CONSTRAINT `fk_Provas_professor1`
    FOREIGN KEY (`professor_idProfessor`)
    REFERENCES `mydb`.`professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`provassub`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`provassub` (
  `idProvasSubstitutivas` INT(11) NOT NULL AUTO_INCREMENT,
  `Disciplina_idDisciplina` INT(11) NOT NULL,
  `alunos_idAlunos` INT(11) NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProvasSubstitutivas`),
  INDEX `fk_provasSubstitutivas_Disciplina1_idx` (`Disciplina_idDisciplina` ASC),
  INDEX `fk_provasSubstitutivas_alunos1_idx` (`alunos_idAlunos` ASC),
  CONSTRAINT `fk_provasSubstitutivas_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `mydb`.`disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_provasSubstitutivas_alunos1`
    FOREIGN KEY (`alunos_idAlunos`)
    REFERENCES `mydb`.`aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`requisicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`requisicao` (
  `idRequisicao` INT(11) NOT NULL AUTO_INCREMENT,
  `justificativaRequisicao` VARCHAR(45) NOT NULL,
  `dataRequisicao` DATETIME NOT NULL,
  `codigoComprovanteRequisicao` VARCHAR(45) NOT NULL,
  `alunos_idAlunos` INT(11) NOT NULL,
  PRIMARY KEY (`idRequisicao`),
  INDEX `fk_Formulario_alunos1_idx` (`alunos_idAlunos` ASC),
  CONSTRAINT `fk_Formulario_alunos1`
    FOREIGN KEY (`alunos_idAlunos`)
    REFERENCES `mydb`.`aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
